<?php
session_start();
include('../layout/header-simple.php');
include('../layout/nav.php');
include('../layout/sidebar.php');
include('../includes/content_semanas_hoteles_equivalencias_index.php');
include('../layout/footer.php');
include('../layout/scripts-presupuesto.php');
?>
