<?php
session_start();
include('../layout/header.php');
include('../layout/nav.php');
include('../layout/sidebar.php');
include('../layout/content-locations.php');
include('../layout/footer.php');
include('../layout/scripts-presupuesto.php');
?>
